
services:
  ia03-db:
    image: postgres:17.5-alpine 
    container_name: ia03-db
    
    environment:
      POSTGRES_USER: user     
      POSTGRES_PASSWORD: pass  
      POSTGRES_DB: ia03_db
    

    ports:
      - "5432:5432"
    

    volumes:
      - postgres-data:/var/lib/postgresql/data
    
    restart: always

volumes:
  postgres-data: